blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://combatcatstudio.github.io/WildAssaultHelp
    about: Check to see if your question is already answered in the FAQ.
  - name: Support Tickets
    url: https://canary.discord.com/channels/1209429896317771796/1237181636446257263
    about: Please submit reports with personal information via Discord tickets.
  - name: Discord Community
    url: https://discord.gg/WildAssault
    about: Some simple questions can also be answered by our community in Discord.
